Repository yewstack/yew, pull requests merged in 2019-10, with the labels that each got.

#563 Add render method to Component and auto implement Renderable
  README.md
  crates/macro/src/lib.rs
  examples/counter/src/lib.rs
  examples/crm/src/lib.rs
  examples/custom_components/src/barrier.rs
  examples/custom_components/src/button.rs
  examples/custom_components/src/counter.rs
  examples/custom_components/src/lib.rs
  examples/dashboard/src/lib.rs
  examples/file_upload/src/lib.rs
  examples/fragments/src/lib.rs
  examples/game_of_life/src/lib.rs
  examples/inner_html/src/lib.rs
  examples/js_callback/src/lib.rs
  examples/large_table/src/lib.rs
  examples/minimal/src/lib.rs
  examples/mount_point/src/lib.rs
  examples/multi_thread/src/lib.rs
  examples/nested_list/src/header.rs
  examples/nested_list/src/item.rs
  examples/nested_list/src/lib.rs
  examples/nested_list/src/list.rs
  examples/npm_and_rest/src/lib.rs
  examples/routing/src/b_component.rs
  examples/routing/src/lib.rs
  examples/routing/src/router_button.rs
  examples/showcase/src/main.rs
  examples/textarea/src/lib.rs
  examples/timer/src/lib.rs
  examples/todomvc/src/lib.rs
  examples/two_apps/src/lib.rs
  src/app.rs
  src/components/select.rs
  src/html/listener.rs
  src/html/mod.rs
  src/html/scope.rs
  src/lib.rs
  src/services/fetch.rs
  src/virtual_dom/vcomp.rs
  src/virtual_dom/vnode.rs
  tests/macro/helpers.rs
  tests/macro/html-component-fail.rs
  tests/macro/html-component-fail.stderr
  tests/macro/html-component-pass.rs
  tests/macro/html-iterable-pass.rs
  tests/macro/test_component.rs
  tests/vcomp_test.rs
  tests/vlist_test.rs
  tests/vtag_test.rs
  tests/vtext_test.rs
Labels: breaking change, ergonomics

#689 Fix multi_thread example
  examples/multi_thread/Cargo.toml
  examples/multi_thread/README.md
  examples/multi_thread/Web.toml
  examples/multi_thread/static/bin
Labels: example

#675 Box VTag to reduce size disparity between VNode variants
  crates/macro/src/html_tree/html_tag/mod.rs
  examples/crm/README.md
  examples/crm/src/markdown.rs
  src/virtual_dom/vnode.rs
  src/virtual_dom/vtag.rs
Labels: breaking change
