Repository yewstack/yew, pull requests merged in 2019-09, with the labels that each got.

#651 Fix VNode orphaning inside of VTags
  src/virtual_dom/vtag.rs
Labels: bug

#639 Add Dispatchers
  examples/routing/src/b_component.rs
  examples/routing/src/lib.rs
  examples/routing/src/router_button.rs
  src/agent.rs
Labels: ergonomics

#596 Early msgs queue for Public worker
  src/agent.rs
Labels: feature

#660 Add a method to emit multiple messages in one callback
  src/html/mod.rs
  src/html/scope.rs
Labels: feature

#319 Remove Transferable trait
  examples/multi_thread/src/context.rs
  examples/multi_thread/src/job.rs
  examples/multi_thread/src/native_worker.rs
  examples/routing/src/router.rs
  src/agent.rs
  src/lib.rs
  src/prelude.rs
Labels: breaking change

#672 Implement Default for VNode
  src/virtual_dom/vnode.rs
Labels: ergonomics
