Repository yewstack/yew, pull requests merged in 2020-07, with the labels that each got.

#1382 Make more service's methods static
  examples/file_upload/src/lib.rs
  yew-stdweb/examples/file_upload/src/lib.rs
  yew/src/services/reader/std_web.rs
  yew/src/services/reader/web_sys.rs
  yew/src/services/resize.rs
Labels: breaking change

#1411 Add access to the event in InputData
  yew/src/html/listener/listener_stdweb.rs
  yew/src/html/listener/listener_web_sys.rs
  yew/src/html/listener/mod.rs
Labels: breaking change

#1409 amendment of todomvc example
  examples/todomvc/Cargo.toml
  examples/todomvc/README.md
  examples/todomvc/src/lib.rs
  examples/todomvc/src/main.rs
  examples/todomvc/static/index.html
Labels: automerge

#1425 Add documentation issue template.
  .github/ISSUE_TEMPLATE/documentation.md
Labels: documentation

#1423 Finish setup of docusaurus
  docs/INTRODUCTION.md
  docs/advanced-topics/how-it-works.md
  docs/advanced-topics/optimizations.md
  docs/concepts/agents.md
  docs/concepts/components/README.md
  docs/concepts/components/callbacks.md
  docs/concepts/components/properties.md
  docs/concepts/components/refs.md
  docs/concepts/html/README.md
  docs/concepts/html/components.md
  docs/concepts/html/elements.md
  docs/concepts/html/lists.md
  docs/concepts/html/literals-and-expressions.md
  docs/concepts/router.md
  docs/concepts/services/README.md
  docs/concepts/services/format.md
  docs/getting-started/build-a-sample-app.md
  docs/getting-started/choose-web-library.md
  docs/getting-started/examples.md
  docs/getting-started/project-setup/README.md
  docs/getting-started/project-setup/using-cargo-web.md
  docs/getting-started/project-setup/using-wasm-bindgen.md
  docs/getting-started/project-setup/using-wasm-pack.md
  docs/getting-started/starter-templates.md
  docs/more/css.md
  docs/more/debugging.md
  docs/more/external-libs.md
  docs/more/roadmap.md
  docs/more/testing.md
  website/i18n/en.json
  website/package.json
  website/sidebars.json
  website/siteConfig.js
  website/static/css/admonition.css
  website/static/css/custom.css
Labels: documentation

#1440 Rewrite the README file for the examples
  examples/README.md
  examples/run_example.sh
Labels: example

#1437 added documentation to explain how to use wasm-bindgen to build an app
  docs/getting-started/project-setup/using-wasm-bindgen.md
Labels: documentation
