Repository yewstack/yew, pull requests merged in 2020-05, with the labels that each got.

#1173 Remove server projects from workspace
  Cargo.toml
Labels: automerge

#1202 Reorganize agents module
  yew/src/agent.rs
  yew/src/agent/link.rs
  yew/src/agent/local/context.rs
  yew/src/agent/local/job.rs
  yew/src/agent/local/mod.rs
  yew/src/agent/mod.rs
  yew/src/agent/pool.rs
  yew/src/agent/worker/mod.rs
  yew/src/agent/worker/private.rs
  yew/src/agent/worker/public.rs
  yew/src/lib.rs
Labels: breaking change

#1206 Stop inlining re-export documentation
  yew/src/services/fetch/std_web.rs
  yew/src/services/fetch/web_sys.rs
  yew/src/services/reader/web_sys.rs
Labels: automerge

#1211 Removed method destroy, replaced it with a drop implementation
  yew-functional/src/lib.rs
  yew/src/html/mod.rs
  yew/src/html/scope.rs
Labels: breaking change

#1195 Conditially require serialize
  .travis.yml
  README.md
  examples/multi_thread/src/context.rs
  examples/multi_thread/src/job.rs
  examples/multi_thread/src/native_worker.rs
  examples/pub_sub/src/event_bus.rs
  yew-router/src/agent/mod.rs
  yew-stdweb/examples/multi_thread/src/context.rs
  yew-stdweb/examples/multi_thread/src/job.rs
  yew-stdweb/examples/multi_thread/src/native_worker.rs
  yew/src/agent/local/context.rs
  yew/src/agent/local/job.rs
  yew/src/agent/mod.rs
  yew/src/agent/pool.rs
  yew/src/agent/worker/mod.rs
  yew/src/agent/worker/private.rs
  yew/src/agent/worker/public.rs
Labels: breaking change

#1226 Prep v0.16.1 release
  CHANGELOG.md
  yew-components/Cargo.toml
  yew-macro/Cargo.toml
  yew-router/Cargo.toml
  yew-stdweb/Cargo.toml
  yew/Cargo.toml
Labels: automerge

#1229 Prep v0.16.2 release
  CHANGELOG.md
  yew-stdweb/Cargo.toml
  yew/Cargo.toml
Labels: automerge

#1235 Make fetch service methods static.
  examples/dashboard/src/lib.rs
  examples/npm_and_rest/src/gravatar.rs
  yew-stdweb/examples/npm_and_rest/src/gravatar.rs
  yew/src/services/fetch.rs
  yew/src/services/fetch/std_web.rs
  yew/src/services/fetch/web_sys.rs
Labels: breaking change

#1244 Allow all global event handlers to be used as listeners
  examples/todomvc/src/lib.rs
  yew-macro/Cargo.toml
  yew-macro/src/html_tree/html_tag/tag_attributes.rs
  yew-stdweb/Cargo.toml
  yew-stdweb/examples/todomvc/src/lib.rs
  yew/Cargo.toml
  yew/src/html/listener/listener_stdweb.rs
  yew/src/html/listener/listener_web_sys.rs
  yew/src/lib.rs
Labels: breaking change

#1256 Fix default event stop propagation behaviour
  yew/src/html/listener/macros.rs
Labels: automerge, breaking change

#1276 Rename vcomp element to parent
  yew/src/html/scope.rs
  yew/src/virtual_dom/vcomp.rs
Labels: automerge
