Repository yewstack/yew, pull requests merged in 2020-01, with the labels that each got.

#844 Remove redundant class string is_empty checks
  src/virtual_dom/mod.rs
  src/virtual_dom/vtag.rs
Labels: performance

#840 Fix handling of boolean attributes
  crates/macro/src/html_tree/html_tag/mod.rs
  crates/macro/src/html_tree/html_tag/tag_attributes.rs
Labels: bug

#894 Install wasm-bindgen-cli if it does not exist on CI
  .travis.yml
Labels: ci
