Repository yewstack/yew, pull requests merged in 2020-04, with the labels that each got.

#1071 Make Component::change impl mandatory
  crates/macro/src/lib.rs
  crates/macro/tests/macro/html-component-fail.rs
  crates/macro/tests/macro/html-component-fail.stderr
  crates/macro/tests/macro/html-component-pass.rs
  examples/crm/src/lib.rs
  examples/custom_components/src/lib.rs
  examples/dashboard/src/lib.rs
  examples/fragments/src/lib.rs
  examples/game_of_life/src/lib.rs
  examples/large_table/src/lib.rs
  examples/showcase/src/main.rs
  examples/std_web/counter/src/lib.rs
  examples/std_web/inner_html/src/lib.rs
  examples/std_web/mount_point/src/lib.rs
  examples/std_web/node_refs/src/input.rs
  examples/std_web/node_refs/src/lib.rs
  examples/std_web/npm_and_rest/src/lib.rs
  examples/std_web/todomvc/src/lib.rs
  examples/std_web/two_apps/src/lib.rs
  examples/textarea/src/lib.rs
  examples/timer/src/lib.rs
  examples/web_sys/counter/src/lib.rs
  examples/web_sys/inner_html/src/lib.rs
  examples/web_sys/mount_point/src/lib.rs
  examples/web_sys/node_refs/src/input.rs
  examples/web_sys/node_refs/src/lib.rs
  examples/web_sys/npm_and_rest/src/lib.rs
  examples/web_sys/todomvc/src/lib.rs
  examples/web_sys/two_apps/src/lib.rs
  src/components/select.rs
  src/html/mod.rs
  src/lib.rs
  src/services/fetch/std_web.rs
  src/services/fetch/web_sys.rs
  src/virtual_dom/vcomp.rs
  src/virtual_dom/vlist.rs
  src/virtual_dom/vtag.rs
  src/virtual_dom/vtext.rs
Labels: breaking change

#1130 Remove old cargo file
  examples/old.Cargo.toml
Labels: automerge

#1132 Move components out of core crate
  Cargo.toml
  yew-components/Cargo.toml
  yew-components/src/lib.rs
  yew-components/src/select.rs
  yew-stdweb/Cargo.toml
  yew/src/components/mod.rs
  yew/src/lib.rs
Labels: automerge

#1133 Prep v0.15 release
  CHANGELOG.md
  README.md
  yew-components/Cargo.toml
  yew-macro/Cargo.toml
  yew-stdweb/Cargo.toml
  yew/Cargo.toml
Labels: automerge

#1137 Remove unsafe casting
  yew/src/html/mod.rs
  yew/src/html/scope.rs
  yew/src/virtual_dom/vcomp.rs
Labels: automerge

#1144 Release YewRouter 0.12.1
  yew-router/CHANGELOG.md
  yew-router/Cargo.toml
Labels: router

#1148 Mark re-exports with doc(no_inline) for clarity
  yew/src/lib.rs
  yew/src/services/fetch/web_sys.rs
  yew/src/services/reader/std_web.rs
Labels: automerge

#1156 Remove eager merge feature of mergify
  .mergify.yml
Labels: automerge

#1163 Enable yew-router tests in CI
  ci/run_tests.sh
  yew-router/src/router.rs
Labels: automerge

#1145 Upgrade router's warp server example to use warp v0.2.2
  yew-router/examples/servers/actix/Cargo.toml
  yew-router/examples/servers/warp/Cargo.toml
  yew-router/examples/servers/warp/src/main.rs
Labels: example, router

#1161 Derive Clone on props in Yewtil doctest
  ci/run_tests.sh
  yewtil/src/not_equal_assign.rs
  yewtil/src/pure.rs
Labels: automerge
