Repository yewstack/yew, pull requests merged in 2020-09, with the labels that each got.

#1537 Finish implementation of optional attributes
  ci/run_benchmarks.sh
  docs/concepts/html/elements.md
  yew-macro/src/html_tree/html_component.rs
  yew-macro/src/html_tree/html_dashed_name.rs
  yew-macro/src/html_tree/html_list.rs
  yew-macro/src/html_tree/html_node.rs
  yew-macro/src/html_tree/html_prop.rs
  yew-macro/src/html_tree/html_tag/mod.rs
  yew-macro/src/html_tree/html_tag/tag_attributes.rs
  yew-macro/src/stringify.rs
  yew-macro/tests/macro/html-component-fail.rs
  yew-macro/tests/macro/html-component-fail.stderr
  yew-macro/tests/macro/html-list-fail.rs
  yew-macro/tests/macro/html-list-fail.stderr
  yew-macro/tests/macro/html-tag-fail.rs
  yew-macro/tests/macro/html-tag-fail.stderr
  yew-macro/tests/macro/html-tag-pass.rs
  yew/Cargo.toml
  yew/src/virtual_dom/mod.rs
  yew/src/virtual_dom/vtag.rs
Labels: breaking change

#1540 WIP: I created boid example
  Cargo.toml
  examples/boids/.gitignore
  examples/boids/Cargo.toml
  examples/boids/src/boid.rs
  examples/boids/src/lib.rs
  examples/boids/src/main.rs
  examples/boids/src/vector.rs
Labels: example

#1562 Modified links for documents
  README.md
Labels: documentation

#1561 Show correct usage of ConsoleService in debugging docs
  docs/more/debugging.md
  website/versioned_docs/version-0.17.3/more/debugging.md
Labels: documentation

#1567 Expose websocket error messages on connection failure
  yew/src/services/websocket.rs
Labels: breaking change

#1570 Fix doctest spell check
  .github/workflows/doctests.yml
  .github/workflows/pull-request.yml
  ci/dictionary.txt
  ci/spellcheck.sh
  docs/concepts/html.md
  docs/getting-started/project-setup/using-wasm-bindgen.md
  docs/more/css.md
  docs/more/external-libs.md
  examples/js_callback/README.md
  website/translated_docs/zh-CN/intro.md
  website/translated_docs/zh-CN/version-0.17.3/intro.md
  website/versioned_docs/version-0.17.3/concepts/html.md
  website/versioned_docs/version-0.17.3/getting-started/project-setup/using-wasm-bindgen.md
  website/versioned_docs/version-0.17.3/more/css.md
  yew-stdweb/examples/js_callback/README.md
  yew/src/services/fetch/std_web.rs
Labels: ci

#1571 Doc spelling fixes
  CONTRIBUTING.md
  ci/dictionary.txt
  docs/README.md
  docs/advanced-topics/optimizations.md
  docs/more/testing.md
  website/translated_docs/ja/advanced-topics/optimizations.md
  website/translated_docs/ja/more/testing.md
  website/translated_docs/ja/version-0.17.3/advanced-topics/optimizations.md
  website/translated_docs/ja/version-0.17.3/more/testing.md
  website/translated_docs/zh-CN/advanced-topics/optimizations.md
  website/translated_docs/zh-CN/version-0.17.3/advanced-topics/optimizations.md
  website/translated_docs/zh-TW/advanced-topics/optimizations.md
  website/translated_docs/zh-TW/more/testing.md
  website/translated_docs/zh-TW/version-0.17.3/advanced-topics/optimizations.md
  website/translated_docs/zh-TW/version-0.17.3/more/testing.md
  website/versioned_docs/version-0.17.3/advanced-topics/optimizations.md
  website/versioned_docs/version-0.17.3/more/testing.md
Labels: documentation

#1572 Describe how the `html!` macro works and what a virtual DOM is for
  docs/advanced-topics/how-it-works.md
Labels: automerge, documentation

#1434 Add documentation about the fetch service.
  docs/concepts/services/fetch.md
Labels: documentation

#1582 Host examples on Firebase
  .firebaserc
  .github/workflows/autopublish.yml
  .github/workflows/publish-examples.yml
  examples/game_of_life/Cargo.toml
  examples/router/README.md
  examples/todomvc/README.md
  firebase.json
  yew-macro/Makefile.toml
Labels: example, meta

#1586 Update documentation for the new examples
  docs/concepts/services/fetch.md
  docs/getting-started/build-a-sample-app.md
  docs/getting-started/choose-web-library.md
  docs/getting-started/examples.md
  docs/getting-started/project-setup.md
  docs/getting-started/project-setup/using-trunk.md
  docs/getting-started/project-setup/using-wasm-bindgen.md
  docs/getting-started/project-setup/using-wasm-pack.md
  docs/getting-started/starter-templates.md
  examples/README.md
  examples/boids/README.md
  examples/counter/README.md
  examples/crm/README.md
  examples/dashboard/README.md
  examples/file_upload/README.md
  examples/futures/README.md
  examples/game_of_life/README.md
  examples/inner_html/README.md
  examples/js_callback/README.md
  examples/keyed_list/README.md
  examples/mount_point/README.md
  examples/multi_thread/README.md
  examples/nested_list/README.md
  examples/node_refs/README.md
  examples/pub_sub/README.md
  examples/router/README.md
  examples/store/README.md
  examples/timer/README.md
  examples/todomvc/README.md
  examples/todomvc/index.html
  examples/todomvc/src/main.rs
  examples/todomvc/src/state.rs
  examples/two_apps/README.md
  examples/webgl/README.md
  website/i18n/en.json
  website/package.json
  website/sidebars.json
Labels: documentation

#1593 Fix link in project setup comparison table
  docs/getting-started/project-setup.md
Labels: documentation

#1588 Few improvements for Classes
  examples/futures/src/markdown.rs
  yew-macro/src/html_tree/html_tag/mod.rs
  yew/src/virtual_dom/mod.rs
Labels: breaking change, ergonomics
