Repository yewstack/yew, pull requests merged in 2020-08, with the labels that each got.

#1468 Fix TodoMVC example bugs
  examples/todomvc/src/lib.rs
Labels: example

#1469 Update documentation to use NodeRef::cast
  docs/concepts/components/README.md
  docs/concepts/components/refs.md
  website/translated_docs/zh-CN/concepts/components/README.md
  website/translated_docs/zh-CN/concepts/components/refs.md
  website/translated_docs/zh-TW/concepts/components/README.md
  website/translated_docs/zh-TW/concepts/components/refs.md
Labels: documentation

#1284 Prevent events per default on RouteAnchor/Button
  yew-router/CHANGELOG.md
  yew-router/src/components/router_button.rs
  yew-router/src/components/router_link.rs
Labels: breaking change, router

#1474 Move CI to GitHub Actions
  .github/workflows/autopublish.yml
  .github/workflows/benchmark.yml
  .github/workflows/pull-request.yml
  .mergify.yml
  .travis.yml
  Cargo.toml
  ci/clear_cache.sh
  ci/install_cargo_web.sh
  yew-components/Cargo.toml
  yew-functional/Cargo.toml
  yew-macro/Cargo.toml
  yew-macro/src/derive_props/field.rs
  yew-router/src/matcher/matcher_impl.rs
  yew-stdweb/Cargo.toml
  yew/Cargo.toml
  yew/src/callback.rs
  yew/src/format/cbor.rs
  yew/src/format/msgpack.rs
  yew/src/format/yaml.rs
  yew/src/html/scope.rs
  yew/src/services/fetch.rs
  yew/src/virtual_dom/mod.rs
  yew/src/virtual_dom/vnode.rs
  yewtil/src/fetch/request.rs
Labels: ci

#1452 Remove proc-macro-hack and bump MSRV to 1.45
  README.md
  examples/file_upload/src/lib.rs
  examples/nested_list/src/app.rs
  examples/webgl/src/lib.rs
  yew-components/src/select.rs
  yew-functional/tests/use_context_hook.rs
  yew-macro/Cargo.toml
  yew-macro/src/html_tree/html_component.rs
  yew-macro/src/html_tree/html_iterable.rs
  yew-macro/src/html_tree/html_node.rs
  yew-macro/src/html_tree/html_tag/mod.rs
  yew-macro/src/lib.rs
  yew-macro/tests/macro/html-block-fail.stderr
  yew-macro/tests/macro/html-component-fail.stderr
  yew-macro/tests/macro/html-iterable-fail.stderr
  yew-macro/tests/macro/html-list-fail.stderr
  yew-macro/tests/macro/html-node-fail.stderr
  yew-macro/tests/macro/html-tag-fail.stderr
  yew-router-macro/src/lib.rs
  yew-router/examples/router_component/src/b_component.rs
  yew-router/src/alias.rs
  yew-stdweb/Cargo.toml
  yew/Cargo.toml
  yew/src/html/scope.rs
  yew/src/lib.rs
  yew/src/utils.rs
  yew/src/virtual_dom/vcomp.rs
  yew/src/virtual_dom/vlist.rs
  yew/src/virtual_dom/vtag.rs
  yew/src/virtual_dom/vtext.rs
  yewtil-macro/src/lib.rs
Labels: breaking change

#1480 Simplify unit tests and test the yew-validation crate
  .github/workflows/pull-request.yml
Labels: ci

#1493 Add GitLocalize and docs links to README
  README.md
Labels: documentation

#1494 Add translation recruiting link
  website/siteConfig.js
Labels: documentation

#1519 Make the examples more self-contained
  examples/README.md
  examples/common/Cargo.toml
  examples/common/src/lib.rs
  examples/crm/Cargo.toml
  examples/crm/src/lib.rs
  examples/dashboard/README.md
  examples/dashboard/server/Cargo.toml
  examples/dashboard/server/src/main.rs
  examples/futures_wp/Cargo.toml
  examples/futures_wp/src/lib.rs
  examples/futures_wp/src/markdown.rs
  examples/run_example.sh
Labels: example

#1517 Remove the Renderable trait
  docs/concepts/html/components.md
  examples/crm/src/lib.rs
  website/translated_docs/ja/concepts/html/components.md
  website/translated_docs/ja/version-0.17.3/concepts/html/components.md
  website/translated_docs/zh-CN/concepts/html/components.md
  website/translated_docs/zh-CN/version-0.17.3/concepts/html/components.md
  website/translated_docs/zh-TW/concepts/html/components.md
  website/translated_docs/zh-TW/version-0.17.3/concepts/html/components.md
  website/versioned_docs/version-0.17.3/concepts/html/components.md
  yew-router/src/router.rs
  yew/src/html/mod.rs
  yew/src/html/scope.rs
  yew/src/lib.rs
  yew/src/services/fetch/std_web.rs
  yew/src/services/fetch/web_sys.rs
  yew/src/virtual_dom/vnode.rs
Labels: breaking change, documentation

#1532 rewrite use
  examples/nested_list/src/list.rs
Labels: example

#1530 Document html_nested! macro and add regression doc-tests for #1527
  yew/src/lib.rs
Labels: documentation

#1525 extend batch_callback for options
  docs/concepts/components/callbacks.md
  examples/todomvc/src/lib.rs
  yew/src/html/mod.rs
  yew/src/html/scope.rs
Labels: breaking change, ergonomics

#1529 yewtil::store send state on connection
  examples/README.md
  examples/store/README.md
  examples/store/src/agents/media_manager.rs
  examples/store/src/agents/mod.rs
  examples/store/src/agents/posts.rs
  examples/store/src/lib.rs
  examples/store/src/post.rs
  examples/store/src/text_input.rs
  yewtil/src/store.rs
Labels: example
