Repository yewstack/yew, pull requests merged in 2020-11, with the labels that each got.

#1640 Fix missing redirects
  website/pages/en/404.js
  website/pages/en/index.js
  website/siteConfig.js
  website/static/index.html
Labels: documentation

#1638 Add macro for generating functional components
  Cargo.toml
  ci/dictionary.txt
  docs/advanced-topics/optimizations.md
  docs/concepts/function-components.md
  docs/concepts/function-components/attribute.md
  docs/concepts/function-components/custom-hooks.md
  docs/concepts/function-components/pre-defined-hooks.md
  website/i18n/en.json
  website/sidebars.json
  yew-functional-macro/Cargo.toml
  yew-functional-macro/Makefile.toml
  yew-functional-macro/src/lib.rs
  yew-functional-macro/tests/function_attr/applied-to-non-fn-fail.rs
  yew-functional-macro/tests/function_attr/applied-to-non-fn-fail.stderr
  yew-functional-macro/tests/function_attr/async-fail.rs
  yew-functional-macro/tests/function_attr/async-fail.stderr
  yew-functional-macro/tests/function_attr/bad-name-fail.rs
  yew-functional-macro/tests/function_attr/bad-name-fail.stderr
  yew-functional-macro/tests/function_attr/bad-props-param-fail.rs
  yew-functional-macro/tests/function_attr/bad-props-param-fail.stderr
  yew-functional-macro/tests/function_attr/bad-return-type-fail.rs
  yew-functional-macro/tests/function_attr/bad-return-type-fail.stderr
  yew-functional-macro/tests/function_attr/const-fail.rs
  yew-functional-macro/tests/function_attr/const-fail.stderr
  yew-functional-macro/tests/function_attr/extern-fail.rs
  yew-functional-macro/tests/function_attr/extern-fail.stderr
  yew-functional-macro/tests/function_attr/generic-fail.rs
  yew-functional-macro/tests/function_attr/generic-fail.stderr
  yew-functional-macro/tests/function_attr/lifetime-props-param-fail.rs
  yew-functional-macro/tests/function_attr/lifetime-props-param-fail.stderr
  yew-functional-macro/tests/function_attr/multiple-param-fail.rs
  yew-functional-macro/tests/function_attr/multiple-param-fail.stderr
  yew-functional-macro/tests/function_attr/mut-ref-props-param-fail.rs
  yew-functional-macro/tests/function_attr/mut-ref-props-param-fail.stderr
  yew-functional-macro/tests/function_attr/no-name-fail.rs
  yew-functional-macro/tests/function_attr/no-name-fail.stderr
  yew-functional-macro/tests/function_attr/with-props-pass.rs
  yew-functional-macro/tests/function_attr/with-receiver-fail.rs
  yew-functional-macro/tests/function_attr/with-receiver-fail.stderr
  yew-functional-macro/tests/function_attr/without-props-pass.rs
  yew-functional-macro/tests/function_attr_test.rs
  yew-functional/Cargo.toml
  yew-functional/src/lib.rs
  yew-functional/src/use_context_hook.rs
Labels: ergonomics, macro

#1616 Variants derive macro
  docs/concepts/components/children.md
  website/sidebars.json
Labels: documentation

#1643 Add docs for Hooks
  docs/concepts/function-components.md
  docs/concepts/function-components/custom-hooks.md
  docs/concepts/function-components/pre-defined-hooks.md
  yew-functional/src/lib.rs
  yew-functional/src/use_context_hook.rs
Labels: documentation

#1651 Apply new Clippy lints, examples deployment, and stdweb integration tests
  .github/workflows/publish-examples.yml
  .github/workflows/pull-request.yml
  examples/futures/src/markdown.rs
  yew-macro/src/props/element.rs
  yew-router-route-parser/src/error.rs
  yew-router/src/switch.rs
  yew-validation/src/lib.rs
Labels: meta

#1650 Improve the "keyed_list" example
  examples/keyed_list/Cargo.toml
  examples/keyed_list/index.html
  examples/keyed_list/src/main.rs
  examples/keyed_list/src/person.rs
  examples/keyed_list/src/random.rs
  examples/keyed_list/styles.css
Labels: example

#1601 Extract Classes to a separate macro
  docs/concepts/html.md
  docs/concepts/html/classes.md
  docs/concepts/html/elements.md
  examples/crm/src/add_client.rs
  examples/futures/src/markdown.rs
  examples/game_of_life/src/main.rs
  examples/nested_list/src/list.rs
  examples/router/src/components/pagination.rs
  examples/router/src/main.rs
  examples/todomvc/src/main.rs
  website/i18n/en.json
  website/sidebars.json
  yew-macro/src/classes/mod.rs
  yew-macro/src/html_tree/html_element.rs
  yew-macro/src/lib.rs
  yew-macro/src/props/element.rs
  yew-macro/tests/classes_macro/classes-fail.rs
  yew-macro/tests/classes_macro/classes-fail.stderr
  yew-macro/tests/classes_macro/classes-pass.rs
  yew-macro/tests/classes_macro_test.rs
  yew-macro/tests/derive_props_test.rs
  yew-macro/tests/html_macro/html-block-fail.rs
  yew-macro/tests/html_macro/html-block-fail.stderr
  yew-macro/tests/html_macro/html-block-pass.rs
  yew-macro/tests/html_macro/html-component-fail.rs
  yew-macro/tests/html_macro/html-component-fail.stderr
  yew-macro/tests/html_macro/html-component-pass.rs
  yew-macro/tests/html_macro/html-component-unimplemented-fail.rs
  yew-macro/tests/html_macro/html-component-unimplemented-fail.stderr
  yew-macro/tests/html_macro/html-element-fail.rs
  yew-macro/tests/html_macro/html-element-fail.stderr
  yew-macro/tests/html_macro/html-element-pass.rs
  yew-macro/tests/html_macro/html-iterable-fail.rs
  yew-macro/tests/html_macro/html-iterable-fail.stderr
  yew-macro/tests/html_macro/html-iterable-pass.rs
  yew-macro/tests/html_macro/html-list-fail.rs
  yew-macro/tests/html_macro/html-list-fail.stderr
  yew-macro/tests/html_macro/html-list-pass.rs
  yew-macro/tests/html_macro/html-node-fail.rs
  yew-macro/tests/html_macro/html-node-fail.stderr
  yew-macro/tests/html_macro/html-node-pass.rs
  yew-macro/tests/html_macro_test.rs
  yew-macro/tests/macro_test.rs
  yew-macro/tests/props_macro_test.rs
  yew/src/html/classes.rs
  yew/src/html/mod.rs
  yew/src/lib.rs
  yew/src/prelude.rs
  yew/src/virtual_dom/mod.rs
  yew/src/virtual_dom/vtag.rs
Labels: breaking change, ergonomics, macro
