Repository yewstack/yew, pull requests merged in 2020-10, with the labels that each got.

#1597 Use --public-url value in router example
  .github/workflows/publish-examples.yml
  .gitignore
  Cargo.toml
  examples/.gitignore
  examples/router/Cargo.toml
  examples/router/README.md
  examples/router/index.html
  examples/router/src/switch.rs
Labels: example

#1596 Tidy up components docs.
  docs/concepts/components.md
Labels: documentation

#1595 Add master docs link to readme
  README.md
Labels: documentation, meta

#1608 Use Firebase channels for preview deploys
  .github/workflows/preview-website.yml
  .github/workflows/publish-examples.yml
  .github/workflows/publish-website.yml
Labels: documentation, meta

#1610 Fix Firebase deployment issues
  .github/workflows/preview-website.yml
  .github/workflows/publish-examples.yml
  .github/workflows/publish-website.yml
Labels: meta

#1611 Contributing md update
  CONTRIBUTING.md
Labels: meta

#1612 Firebase Part 3
  .github/workflows/preview-website.yml
  .github/workflows/publish-examples.yml
  .github/workflows/publish-website.yml
Labels: meta

#1614 Update to Trunk 0.7
  .github/workflows/preview-website.yml
  .github/workflows/publish-examples.yml
  .github/workflows/publish-website.yml
  examples/boids/index.html
  examples/dashboard/index.html
  examples/game_of_life/index.html
  examples/js_callback/index.html
  examples/keyed_list/index.html
  examples/multi_thread/README.md
  examples/multi_thread/index.html
  examples/nested_list/index.html
  examples/router/index.html
Labels: example

#1618 Clean up .gitignore files
  .gitignore
  docs/.gitignore
  examples/.gitignore
  website/.gitignore
  website/translated_docs/zh-TW/.gitignore
Labels: meta

#1619 Separate build and publish workflows for website
  .github/workflows/build-website.yml
  .github/workflows/preview-website.yml
  .github/workflows/publish-website.yml
  docs/SUMMARY.md
Labels: meta

#1617 Add a ticking clock to the timer example.
  examples/timer/Cargo.toml
  examples/timer/README.md
  examples/timer/index.html
  examples/timer/index.scss
  examples/timer/src/main.rs
Labels: example

#1621 Correct documentation redirects (and fix the workflow)
  .github/workflows/build-website.yml
  .github/workflows/publish-website.yml
  README.md
  docs/index.md
  firebase.json
  website/i18n/en.json
  website/i18n/ja.json
  website/i18n/zh-CN.json
  website/i18n/zh-TW.json
  website/pages/en/versions.js
  website/sidebars.json
  website/static/index.html
  website/translated_docs/ja/SUMMARY.md
  website/translated_docs/ja/index.md
  website/translated_docs/ja/version-0.17.3/SUMMARY.md
  website/translated_docs/ja/version-0.17.3/index.md
  website/translated_docs/zh-CN/index.md
  website/translated_docs/zh-CN/version-0.17.3/index.md
  website/translated_docs/zh-TW/index.md
  website/translated_docs/zh-TW/version-0.17.3/index.md
  website/versioned_docs/version-0.17.3/index.md
  website/versioned_sidebars/version-0.17.3-sidebars.json
Labels: documentation, meta

#1599 Add a macro for building properties outside of html!
  .github/workflows/pull-request.yml
  ci/dictionary.txt
  ci/spellcheck.sh
  docs/concepts/components.md
  docs/concepts/components/properties.md
  docs/concepts/html.md
  docs/concepts/html/components.md
  docs/concepts/html/elements.md
  docs/getting-started/project-setup.md
  yew-components/src/select.rs
  yew-macro/src/html_tree/html_block.rs
  yew-macro/src/html_tree/html_component.rs
  yew-macro/src/html_tree/html_dashed_name.rs
  yew-macro/src/html_tree/html_element.rs
  yew-macro/src/html_tree/html_iterable.rs
  yew-macro/src/html_tree/html_list.rs
  yew-macro/src/html_tree/html_prop.rs
  yew-macro/src/html_tree/mod.rs
  yew-macro/src/html_tree/tag.rs
  yew-macro/src/lib.rs
  yew-macro/src/props/component.rs
  yew-macro/src/props/element.rs
  yew-macro/src/props/mod.rs
  yew-macro/src/props/prop.rs
  yew-macro/src/props/prop_macro.rs
  yew-macro/tests/macro/html-component-fail.rs
  yew-macro/tests/macro/html-component-fail.stderr
  yew-macro/tests/macro/html-component-pass.rs
  yew-macro/tests/macro/html-element-fail.rs
  yew-macro/tests/macro/html-element-fail.stderr
  yew-macro/tests/macro/html-element-pass.rs
  yew-macro/tests/macro/html-list-fail.stderr
  yew-macro/tests/macro/test_component.rs
  yew-macro/tests/macro_test.rs
  yew-macro/tests/props_macro/props-fail.rs
  yew-macro/tests/props_macro/props-fail.stderr
  yew-macro/tests/props_macro/props-pass.rs
  yew-macro/tests/props_macro/resolve-prop-fail.rs
  yew-macro/tests/props_macro/resolve-prop-fail.stderr
  yew-macro/tests/props_macro/resolve-prop-pass.rs
  yew-macro/tests/props_macro_test.rs
  yew-router/src/components/router_button.rs
  yew-router/src/components/router_link.rs
  yew/src/html/mod.rs
  yew/src/lib.rs
  yew/src/virtual_dom/vcomp.rs
  yew/src/virtual_dom/vtag.rs
  yewtil/src/store.rs
Labels: breaking change, ergonomics, macro

#1628 Document dynamic tag names
  ci/dictionary.txt
  docs/concepts/html/elements.md
  docs/getting-started/project-setup.md
Labels: documentation
