Repository yewstack/yew, pull requests merged in 2020-06, with the labels that each got.

#1218 Release v0.13 of the router
  yew-router-macro/Cargo.toml
  yew-router-route-parser/Cargo.toml
  yew-router/CHANGELOG.md
  yew-router/Cargo.toml
Labels: router

#1275 Unify and change children logic in the html macro
  examples/nested_list/src/item.rs
  yew-functional/src/use_context_hook.rs
  yew-functional/tests/use_context_hook.rs
  yew-macro/src/html_tree/html_block.rs
  yew-macro/src/html_tree/html_component.rs
  yew-macro/src/html_tree/html_iterable.rs
  yew-macro/src/html_tree/html_list.rs
  yew-macro/src/html_tree/html_node.rs
  yew-macro/src/html_tree/html_tag/mod.rs
  yew-macro/src/html_tree/mod.rs
  yew-macro/src/lib.rs
  yew-macro/tests/macro/html-block-fail.stderr
  yew-macro/tests/macro/html-component-fail.rs
  yew-macro/tests/macro/html-component-fail.stderr
  yew-macro/tests/macro/html-component-pass.rs
  yew-macro/tests/macro/html-iterable-fail.rs
  yew-macro/tests/macro/html-iterable-fail.stderr
  yew-macro/tests/macro/html-list-pass.rs
  yew-macro/tests/macro/html-tag-pass.rs
  yew/src/html/mod.rs
  yew/src/utils.rs
  yew/src/virtual_dom/vcomp.rs
  yew/src/virtual_dom/vlist.rs
  yew/src/virtual_dom/vtag.rs
Labels: breaking change

#1279 Refactor VDiff trait to make way for keyed list fixes
  yew/src/app.rs
  yew/src/html/mod.rs
  yew/src/html/scope.rs
  yew/src/virtual_dom/mod.rs
  yew/src/virtual_dom/vcomp.rs
  yew/src/virtual_dom/vlist.rs
  yew/src/virtual_dom/vnode.rs
  yew/src/virtual_dom/vtag.rs
  yew/src/virtual_dom/vtext.rs
Labels: automerge

#1295 Fix master
  yew/src/virtual_dom/vcomp.rs
Labels: automerge

#1296 Speed up vtag diffing
  yew/src/virtual_dom/vtag.rs
Labels: automerge

#1309 Split update and render operations into seprate tasks
  yew-functional/src/lib.rs
  yew-functional/src/use_context_hook.rs
  yew-functional/tests/lib.rs
  yew-functional/tests/use_context_hook.rs
  yew/src/html/scope.rs
  yew/src/scheduler.rs
Labels: automerge, performance

#1333 Refactor VComp to allow access to root vnode
  yew/src/html/mod.rs
  yew/src/html/scope.rs
  yew/src/virtual_dom/vcomp.rs
  yew/src/virtual_dom/vnode.rs
Labels: performance

#1304 Complete some `TODO`s
  yew-router/CHANGELOG.md
  yew-router/src/lib.rs
  yewtil/CHANGELOG.md
  yewtil/src/fetch.rs
  yewtil/src/fetch/action.rs
Labels: breaking change, router

#1337 Fix scope root vnode method
  yew/src/html/scope.rs
Labels: automerge

#1338 Fix key parse bug for components
  yew-macro/src/html_tree/html_component.rs
  yew/src/virtual_dom/vcomp.rs
Labels: automerge

#1341 Add more protection against node ref cycles
  yew/src/html/mod.rs
Labels: automerge

#1313 Make methods static.
  examples/counter/src/lib.rs
  examples/crm/src/lib.rs
  examples/dashboard/src/lib.rs
  examples/game_of_life/src/lib.rs
  examples/multi_thread/src/context.rs
  examples/multi_thread/src/job.rs
  examples/multi_thread/src/native_worker.rs
  examples/npm_and_rest/src/ccxt.rs
  examples/npm_and_rest/src/gravatar.rs
  examples/npm_and_rest/src/lib.rs
  examples/timer/src/lib.rs
  examples/webgl/src/lib.rs
  yew-functional/tests/use_context_hook.rs
  yew-stdweb/examples/counter/src/lib.rs
  yew-stdweb/examples/multi_thread/src/context.rs
  yew-stdweb/examples/multi_thread/src/job.rs
  yew-stdweb/examples/multi_thread/src/native_worker.rs
  yew/src/services/console.rs
  yew/src/services/dialog.rs
  yew/src/services/fetch/std_web.rs
  yew/src/services/fetch/web_sys.rs
  yew/src/services/interval.rs
  yew/src/services/mod.rs
  yew/src/services/render.rs
  yew/src/services/timeout.rs
  yew/src/services/websocket.rs
Labels: breaking change

#1354 Bring back destroy lifecycle method
  yew-functional/src/lib.rs
  yew/src/html/mod.rs
  yew/src/html/scope.rs
Labels: automerge
