Repository yewstack/yew, pull requests merged in 2021-01, with the labels that each got.

#1709 Enable std feature for indexmap
  packages/yew/Cargo.toml
Labels: automerge

#1714 Bump minimum serde_yaml version in order to appease deps.rs
  packages/yew/Cargo.toml
Labels: meta

#1715 Add viewport meta tag to fix mobile version of the TodoMVC example
  examples/todomvc/index.html
Labels: example
