Repository yewstack/yew, pull requests merged in 2021-12, with the labels that each got.

#2228 Fix docs hooks naming
  website/docs/concepts/function-components/introduction.md
  website/versioned_docs/version-0.19.0/concepts/function-components/introduction.md
Labels: documentation

#2194 Fix benchmark yew dependecy version setting step
  .github/workflows/benchmark.yml
Labels: performance, meta

#2235 Add github actions for publishing crates
  .github/workflows/publish-yew-agent.yml
  .github/workflows/publish-yew-router.yml
  .github/workflows/publish-yew.yml
  packages/yew/tests/use_effect.rs
Labels: meta

#2237 Fix publish actions
  .github/workflows/publish-yew-agent.yml
  .github/workflows/publish-yew-router.yml
  .github/workflows/publish-yew.yml
Labels: meta

#2214 Router docs about set-only components
  packages/yew-router/src/components/link.rs
  website/docs/concepts/router.md
Labels: documentation, A-yew-router

#2241 Automatic publishing actions v2
  .github/workflows/publish-yew-agent.yml
  .github/workflows/publish-yew-router.yml
  .github/workflows/publish-yew.yml
  packages/yew-macro/release.toml
  packages/yew-router-macro/release.toml
  release.toml
Labels: meta

#2234 Fix router cargo version in docs
  website/docs/concepts/router.md
  website/versioned_docs/version-0.19.0/concepts/router.md
Labels: documentation

#2243 Add explicit permisions for publish workflows
  .github/workflows/publish-yew-agent.yml
  .github/workflows/publish-yew-router.yml
  .github/workflows/publish-yew.yml
Labels: meta

#2245 (cargo-release) version yew-macro-v0.19.0
  packages/yew-macro/Cargo.toml
  packages/yew/Cargo.toml
Labels: meta

#2248 add back readmes
  packages/yew-agent/Cargo.toml
  packages/yew/Cargo.toml
Labels: meta

#2259 Update token to use bot in publish actions
  .github/workflows/publish-yew-agent.yml
  .github/workflows/publish-yew-only.yml
  .github/workflows/publish-yew-router-only.yml
  .github/workflows/publish-yew-router.yml
  .github/workflows/publish-yew.yml
Labels: meta

#2260 Checkout as bot
  .github/workflows/publish-yew-agent.yml
  .github/workflows/publish-yew-only.yml
  .github/workflows/publish-yew-router-only.yml
  .github/workflows/publish-yew-router.yml
  .github/workflows/publish-yew.yml
Labels: meta

#2261 Fix failed release
  packages/yew-macro/Cargo.toml
  packages/yew/Cargo.toml
  release.toml
Labels: meta

#2262 (cargo-release) version yew-v0.19.2
  packages/yew/Cargo.toml
Labels: meta

#2263 Change path versions to tag versions
  packages/yew-agent/Cargo.toml
  packages/yew-router/Cargo.toml
Labels: meta

#2265 Add paths for yew dependencies
  packages/yew-agent/Cargo.toml
  packages/yew-router/Cargo.toml
Labels: meta

#2274 Move/Remove tools
  .github/workflows/pull-request.yml
  Cargo.toml
  Makefile.toml
  packages/yew-validation/Cargo.toml
  packages/yew-validation/src/lib.rs
  tools/changelog/Cargo.toml
  tools/changelog/Makefile.toml
  tools/changelog/src/main.rs
  tools/website-test/Cargo.toml
  tools/website-test/Makefile.toml
  tools/website-test/build.rs
  tools/website-test/src/agents.rs
  tools/website-test/src/lib.rs
  tools/website-test/src/tutorial.rs
Labels: meta

#2272 simplfy the readme for yew-router
  packages/yew-router/README.md
Labels: documentation

#2273 Raw field names in property structs
  packages/yew-macro/src/derive_props/builder.rs
  packages/yew-macro/src/derive_props/field.rs
  packages/yew-macro/src/derive_props/mod.rs
  packages/yew-macro/tests/derive_props/pass.rs
  packages/yew-macro/tests/html_macro/component-pass.rs
  packages/yew-macro/tests/props_macro/props-pass.rs
Labels: A-yew-macro

#2266 Silence some warnings from derive(Properties)
  packages/yew-macro/src/derive_props/builder.rs
  packages/yew-macro/src/derive_props/field.rs
  packages/yew-macro/src/derive_props/mod.rs
  packages/yew-macro/src/derive_props/wrapper.rs
  packages/yew-macro/tests/derive_props/pass.rs
Labels: A-yew-macro

#2284 Fix defaulted type parameter.
  packages/yew-macro/src/function_component.rs
  packages/yew-macro/tests/function_component_attr/with-defaulted-type-param-pass.rs
Labels: A-yew-macro

#2239 gloo-history based `yew-router`
  examples/router/src/pages/post_list.rs
  packages/yew-router-macro/src/routable_derive.rs
  packages/yew-router-macro/tests/routable_derive/relative-path-fail.rs
  packages/yew-router-macro/tests/routable_derive/relative-path-fail.stderr
  packages/yew-router-macro/tests/routable_derive/route-with-hash-fail.rs
  packages/yew-router-macro/tests/routable_derive/route-with-hash-fail.stderr
  packages/yew-router/Cargo.toml
  packages/yew-router/src/components/link.rs
  packages/yew-router/src/components/redirect.rs
  packages/yew-router/src/history.rs
  packages/yew-router/src/hooks.rs
  packages/yew-router/src/lib.rs
  packages/yew-router/src/navigator.rs
  packages/yew-router/src/router.rs
  packages/yew-router/src/scope_ext.rs
  packages/yew-router/src/switch.rs
  packages/yew-router/src/utils.rs
  packages/yew-router/tests/basename.rs
  packages/yew-router/tests/browser_router.rs
  packages/yew-router/tests/hash_router.rs
  packages/yew-router/tests/history.rs
  packages/yew-router/tests/utils.rs
  website/docs/concepts/router.md
Labels: A-yew-router, A-yew-router-macro

#2279 Fix a problem with NodeRefs and vtags, ref #2206
  packages/yew/src/virtual_dom/vtag.rs
Labels: A-yew

#2286 Automate changelog gen and gh release in actions
  .github/workflows/inspect_next_changelogs.yml
  .github/workflows/publish-yew-agent.yml
  .github/workflows/publish-yew-only.yml
  .github/workflows/publish-yew-router-only.yml
  .github/workflows/publish-yew-router.yml
  .github/workflows/publish-yew.yml
  .github/workflows/pull-request.yml
  tools/changelog/Cargo.toml
  tools/changelog/src/cli.rs
  tools/changelog/src/create_log_line.rs
  tools/changelog/src/create_log_lines.rs
  tools/changelog/src/get_latest_version.rs
  tools/changelog/src/github_fetch.rs
  tools/changelog/src/github_issue_labels_fetcher.rs
  tools/changelog/src/github_user_fetcher.rs
  tools/changelog/src/lib.rs
  tools/changelog/src/log_line.rs
  tools/changelog/src/main.rs
  tools/changelog/src/mod.rs
  tools/changelog/src/new_version_level.rs
  tools/changelog/src/stdout_tag_description_changelog.rs
  tools/changelog/src/write_changelog_file.rs
  tools/changelog/src/write_log_lines.rs
  tools/changelog/src/write_version_changelog.rs
  tools/changelog/src/yew_package.rs
  tools/changelog/tests/generate_yew_changelog_file.rs
  tools/changelog/tests/test_base.md
  tools/changelog/tests/test_expected.md
Labels: meta

#2285 Implement IntoPropValue for Rc<str>
  packages/yew-macro/tests/html_macro/component-fail.stderr
  packages/yew-macro/tests/html_macro/element-fail.stderr
  packages/yew/src/html/conversion.rs
Labels: A-yew

#2288 Bump Docusaurus to beta 14
  packages/yew/src/lib.rs
  website/package-lock.json
  website/package.json
  website/versioned_docs/version-0.19.0/more/development-tips.mdx
Labels: documentation, meta

#2294 delete unused mergify file
  .mergify.yml
Labels: meta

#2292 Allow `function_component` creation based on function name
  examples/function_todomvc/src/components/filter.rs
  packages/yew-macro/src/function_component.rs
  packages/yew-macro/tests/function_component_attr/bad-name-fail.stderr
  packages/yew-macro/tests/function_component_attr/generic-props-fail.stderr
  packages/yew-macro/tests/function_component_attr/no-name-default-pass.rs
  packages/yew-macro/tests/function_component_attr/no-name-fail.stderr
  website/docs/concepts/function-components/attribute.mdx
  website/docs/concepts/function-components/introduction.mdx
Labels: A-yew, A-yew-macro

#2293 Vlist const new
  .gitignore
  packages/yew/src/virtual_dom/vlist.rs
  packages/yew/src/virtual_dom/vtag.rs
Labels: A-yew

#2297 Fix basename handling in router
  packages/yew-router/src/macro_helpers.rs
Labels: bug, A-yew-router

#2300 Add pending event listener on the VTag
  packages/yew/src/virtual_dom/vtag.rs
Labels: A-yew

#2308 auto approve maintainer pr's
  .github/workflows/auto_approve_maintainer_pr.yml
Labels: meta

#2301 Refactor and simplify `Callback`
  examples/function_todomvc/src/components/entry.rs
  examples/function_todomvc/src/components/filter.rs
  examples/function_todomvc/src/hooks/use_bool_toggle.rs
  packages/yew-agent/src/link.rs
  packages/yew/src/callback.rs
  packages/yew/src/html/component/scope.rs
  packages/yew/src/html/listener/events.rs
  packages/yew/src/virtual_dom/listeners.rs
  website/docs/concepts/components/scope.mdx
  website/docs/concepts/router.mdx
Labels: breaking change, A-yew

#2307 Add auth to changelog generation
  .github/workflows/inspect_next_changelogs.yml
  .github/workflows/publish-yew-agent.yml
  .github/workflows/publish-yew-only.yml
  .github/workflows/publish-yew-router-only.yml
  .github/workflows/publish-yew-router.yml
  .github/workflows/publish-yew.yml
  tools/changelog/src/cli.rs
  tools/changelog/src/create_log_line.rs
  tools/changelog/src/create_log_lines.rs
  tools/changelog/src/github_fetch.rs
  tools/changelog/src/github_issue_labels_fetcher.rs
  tools/changelog/src/github_user_fetcher.rs
  tools/changelog/tests/generate_yew_changelog_file.rs
Labels: meta

#2310 Make layout testing code `pub`
  packages/yew/src/lib.rs
  packages/yew/src/tests/layout_tests.rs
  packages/yew/src/tests/mod.rs
  packages/yew/src/virtual_dom/mod.rs
  packages/yew/src/virtual_dom/vcomp.rs
  packages/yew/src/virtual_dom/vlist.rs
  packages/yew/src/virtual_dom/vnode.rs
  packages/yew/src/virtual_dom/vportal.rs
  packages/yew/src/virtual_dom/vtag.rs
  packages/yew/src/virtual_dom/vtext.rs
Labels: A-yew

#2314 fix benchmark action
  .github/workflows/benchmark.yml
Labels: meta

#2306 update example futures pulldown_cmark to v0.9
  examples/futures/Cargo.toml
  examples/futures/src/markdown.rs
Labels: A-examples, dependencies

#2295 Remove context & job agent
  Cargo.toml
  examples/agents/Cargo.toml
  examples/agents/README.md
  examples/agents/index.html
  examples/agents/src/bin/app.rs
  examples/agents/src/bin/worker.rs
  examples/agents/src/lib.rs
  examples/agents/src/native_worker.rs
  examples/contexts/Cargo.toml
  examples/contexts/README.md
  examples/contexts/index.html
  examples/contexts/src/main.rs
  examples/contexts/src/msg_ctx.rs
  examples/contexts/src/producer.rs
  examples/contexts/src/subscriber.rs
  examples/multi_thread/README.md
  examples/multi_thread/src/context.rs
  examples/multi_thread/src/job.rs
  examples/multi_thread/src/lib.rs
  examples/pub_sub/README.md
  examples/pub_sub/index.html
  examples/pub_sub/src/event_bus.rs
  examples/pub_sub/src/main.rs
  examples/pub_sub/src/producer.rs
  examples/pub_sub/src/subscriber.rs
  examples/store/Cargo.toml
  examples/store/README.md
  examples/store/src/agents/mod.rs
  examples/store/src/agents/posts.rs
  examples/store/src/main.rs
  examples/store/src/post.rs
  examples/store/src/text_input.rs
  packages/yew-agent/src/lib.rs
  packages/yew-agent/src/local/context.rs
  packages/yew-agent/src/local/job.rs
  packages/yew-agent/src/local/mod.rs
  packages/yew-agent/src/utils/mod.rs
  packages/yew-agent/src/utils/store.rs
  tools/website-test/Cargo.toml
  tools/website-test/src/agents.rs
  tools/website-test/src/lib.rs
  website/docs/advanced-topics/portals.mdx
  website/docs/concepts/agents.mdx
  website/docs/concepts/function-components/custom-hooks.mdx
  website/docs/concepts/function-components/pre-defined-hooks.mdx
  website/docs/concepts/html/elements.mdx
  website/docs/concepts/html/events.mdx
  website/docs/migration-guides/yew-agent/from-0_1_0-to-0_2_0.mdx
Labels: breaking change, A-yew-agent

#2320 Remove unused yew-router dependencies.
  packages/yew-router/Cargo.toml
Labels: dependencies, A-yew-router

#2186 Remove some unsafes by using atomics
  packages/yew/src/virtual_dom/listeners.rs
  packages/yew/tests/use_state.rs
Labels: performance, blocked, A-yew
