Repository yewstack/yew, pull requests merged in 2022-12, with the labels that each got.

#3019 Point links in docs for 0.20 to stable versions
  website/versioned_docs/version-0.20/advanced-topics/immutable.mdx
  website/versioned_docs/version-0.20/advanced-topics/portals.mdx
  website/versioned_docs/version-0.20/advanced-topics/server-side-rendering.md
  website/versioned_docs/version-0.20/advanced-topics/struct-components/callbacks.mdx
  website/versioned_docs/version-0.20/advanced-topics/struct-components/refs.mdx
  website/versioned_docs/version-0.20/concepts/agents.mdx
  website/versioned_docs/version-0.20/concepts/contexts.mdx
  website/versioned_docs/version-0.20/concepts/function-components/node-refs.mdx
  website/versioned_docs/version-0.20/concepts/html/components.mdx
  website/versioned_docs/version-0.20/concepts/html/elements.mdx
  website/versioned_docs/version-0.20/concepts/html/lists.mdx
  website/versioned_docs/version-0.20/concepts/router.mdx
  website/versioned_docs/version-0.20/concepts/suspense.mdx
  website/versioned_docs/version-0.20/getting-started/examples.mdx
  website/versioned_docs/version-0.20/migration-guides/yew-agent/from-0_1_0-to-0_2_0.mdx
  website/versioned_docs/version-0.20/tutorial/index.mdx
Labels: documentation

#2913 Mention certain components must be children of Router
  website/docs/concepts/router.mdx
  website/versioned_docs/version-0.19.0/concepts/router.mdx
  website/versioned_docs/version-0.20/concepts/router.mdx
Labels: documentation

#3021 Make Classes cheap to clone
  packages/yew-macro/tests/classes_macro/classes-fail.stderr
  packages/yew/src/html/classes.rs
Labels: A-yew

#3020 Fix top-level reconciliation in portals
  packages/yew/src/dom_bundle/bportal.rs
Labels: A-yew

#3026 Consolidate publish workflows into one
  .github/workflows/publish-yew-agent.yml
  .github/workflows/publish-yew-router-only.yml
  .github/workflows/publish-yew-router.yml
  .github/workflows/publish-yew.yml
  .github/workflows/publish.yml
Labels: A-ci, meta

#3028 update migration docs to be more explicit
  website/versioned_docs/version-0.20/migration-guides/yew/from-0_19_0-to-0_20_0.mdx
Labels: documentation

#3027 Update benchmark crates and workflow
  .github/workflows/benchmark.yml
  .github/workflows/post-benchmark.yml
  tools/Cargo.lock
  tools/benchmark-hooks/Cargo.toml
  tools/benchmark-hooks/package-lock.json
  tools/benchmark-hooks/package.json
  tools/benchmark-hooks/src/lib.rs
  tools/benchmark-struct/Cargo.toml
  tools/benchmark-struct/package-lock.json
  tools/benchmark-struct/package.json
  tools/benchmark-struct/src/lib.rs
Labels: performance

#3065 Use SVG for logo on website
  website/docusaurus.config.js
  website/static/img/logo.svg
Labels: meta
