Repository yewstack/yew, pull requests merged in 2022-02, with the labels that each got.

#2422 docs: added a screenshot of an example
  website/docs/tutorial/index.mdx
  website/static/img/tutorial_application_screenshot.png
  website/versioned_docs/version-0.19.0/tutorial/index.mdx
Labels: documentation

#2434 Convert components concept docs from SC to FC
  packages/yew/src/functional/mod.rs
  website/docs/advanced-topics/children.mdx
  website/docs/advanced-topics/struct-components/callbacks.mdx
  website/docs/advanced-topics/struct-components/hoc.mdx
  website/docs/advanced-topics/struct-components/introduction.mdx
  website/docs/advanced-topics/struct-components/lifecycle.mdx
  website/docs/advanced-topics/struct-components/properties.mdx
  website/docs/advanced-topics/struct-components/refs.mdx
  website/docs/advanced-topics/struct-components/scope.mdx
  website/docs/concepts/basic-web-technologies/css.mdx
  website/docs/concepts/basic-web-technologies/html.mdx
  website/docs/concepts/basic-web-technologies/js.mdx
  website/docs/concepts/contexts.mdx
  website/docs/concepts/function-components/attribute.mdx
  website/docs/concepts/function-components/callbacks.mdx
  website/docs/concepts/function-components/children.mdx
  website/docs/concepts/function-components/communication.mdx
  website/docs/concepts/function-components/generics.mdx
  website/docs/concepts/function-components/hooks/custom-hooks.mdx
  website/docs/concepts/function-components/hooks/introduction.mdx
  website/docs/concepts/function-components/hooks/use-context.mdx
  website/docs/concepts/function-components/hooks/use-effect.mdx
  website/docs/concepts/function-components/hooks/use-memo.mdx
  website/docs/concepts/function-components/hooks/use-mut-ref.mdx
  website/docs/concepts/function-components/hooks/use-node-ref.mdx
  website/docs/concepts/function-components/hooks/use-reducer.mdx
  website/docs/concepts/function-components/hooks/use-state.mdx
  website/docs/concepts/function-components/introduction.mdx
  website/docs/concepts/function-components/node-refs.mdx
  website/docs/concepts/function-components/pre-defined-hooks.mdx
  website/docs/concepts/function-components/properties.mdx
  website/docs/concepts/function-components/pure-components.mdx
  website/docs/concepts/function-components/state.mdx
  website/docs/concepts/suspense.mdx
  website/docs/getting-started/introduction.mdx
  website/i18n/ja/docusaurus-plugin-content-docs/current.json
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  website/i18n/zh-TW/docusaurus-plugin-content-docs/current.json
  website/sidebars/docs.js
Labels: documentation

#2421 Automatic Message Batching
  packages/yew-router/tests/basename.rs
  packages/yew-router/tests/browser_router.rs
  packages/yew-router/tests/hash_router.rs
  packages/yew/src/html/component/lifecycle.rs
  packages/yew/src/html/component/scope.rs
  packages/yew/src/scheduler.rs
  packages/yew/src/tests/layout_tests.rs
  packages/yew/src/virtual_dom/listeners.rs
  packages/yew/src/virtual_dom/vcomp.rs
  packages/yew/tests/mod.rs
  packages/yew/tests/suspense.rs
  packages/yew/tests/use_context.rs
  packages/yew/tests/use_effect.rs
  packages/yew/tests/use_memo.rs
  packages/yew/tests/use_reducer.rs
  packages/yew/tests/use_ref.rs
  packages/yew/tests/use_state.rs
  website/docs/migration-guides/yew/from-0_19_0-to-0_20_0.mdx
Labels: breaking change, A-yew

#2469 Make small fix to tutorial to reduce redundancy
  website/docs/tutorial/index.mdx
Labels: documentation

#2445 Improve AnyScope API
  packages/yew/src/html/component/scope.rs
Labels: A-yew
