Repository yewstack/yew, pull requests merged in 2022-01, with the labels that each got.

#2318 Implement PrivateAgent
  examples/agents/src/bin/worker.rs
  examples/web_worker_fib/src/lib.rs
  packages/yew-agent/src/lib.rs
  packages/yew-agent/src/worker/mod.rs
  packages/yew-agent/src/worker/private.rs
  packages/yew-agent/src/worker/public.rs
  website/docs/concepts/agents.mdx
  website/docs/migration-guides/yew-agent/from-0_1_0-to-0_2_0.mdx
Labels: A-yew-agent

#2212 Suspense Support
  Cargo.toml
  examples/function_todomvc/src/components/entry.rs
  examples/function_todomvc/src/components/filter.rs
  examples/function_todomvc/src/components/header_input.rs
  examples/function_todomvc/src/components/info_footer.rs
  examples/function_todomvc/src/main.rs
  examples/suspense/Cargo.toml
  examples/suspense/README.md
  examples/suspense/index.html
  examples/suspense/index.scss
  examples/suspense/src/main.rs
  examples/suspense/src/use_sleep.rs
  packages/yew-macro/src/function_component.rs
  packages/yew-macro/src/html_tree/html_component.rs
  packages/yew-macro/tests/function_component_attr/bad-name-fail.stderr
  packages/yew-macro/tests/function_component_attr/bad-return-type-fail.stderr
  packages/yew-macro/tests/function_component_attr/generic-pass.rs
  packages/yew-macro/tests/function_component_attr/generic-props-fail.stderr
  packages/yew-macro/tests/html_macro/component-unimplemented-fail.stderr
  packages/yew/Cargo.toml
  packages/yew/src/app_handle.rs
  packages/yew/src/functional/hooks/use_ref.rs
  packages/yew/src/functional/mod.rs
  packages/yew/src/html/component/lifecycle.rs
  packages/yew/src/html/component/mod.rs
  packages/yew/src/html/component/scope.rs
  packages/yew/src/html/conversion.rs
  packages/yew/src/html/error.rs
  packages/yew/src/html/mod.rs
  packages/yew/src/lib.rs
  packages/yew/src/sealed.rs
  packages/yew/src/suspense/component.rs
  packages/yew/src/suspense/mod.rs
  packages/yew/src/suspense/suspension.rs
  packages/yew/src/virtual_dom/mod.rs
  packages/yew/src/virtual_dom/vcomp.rs
  packages/yew/src/virtual_dom/vlist.rs
  packages/yew/src/virtual_dom/vnode.rs
  packages/yew/src/virtual_dom/vportal.rs
  packages/yew/src/virtual_dom/vsuspense.rs
  packages/yew/src/virtual_dom/vtag.rs
  packages/yew/src/virtual_dom/vtext.rs
  packages/yew/tests/mod.rs
  packages/yew/tests/suspense.rs
  packages/yew/tests/use_context.rs
  packages/yew/tests/use_effect.rs
  packages/yew/tests/use_reducer.rs
  packages/yew/tests/use_ref.rs
  packages/yew/tests/use_state.rs
  website/docs/advanced-topics/portals.mdx
  website/docs/concepts/function-components/attribute.mdx
  website/docs/concepts/function-components/introduction.mdx
  website/docs/concepts/function-components/pre-defined-hooks.mdx
  website/docs/concepts/suspense.md
  website/sidebars.js
Labels: breaking change, A-yew, A-yew-macro

#2326 Move yew-agent to gloo
  examples/agents/src/bin/worker.rs
  examples/agents/src/lib.rs
  examples/agents/src/native_worker.rs
  examples/web_worker_fib/src/agent.rs
  examples/web_worker_fib/src/app.rs
  examples/web_worker_fib/src/lib.rs
  packages/yew-agent/Cargo.toml
  packages/yew-agent/src/hooks.rs
  packages/yew-agent/src/lib.rs
  packages/yew-agent/src/link.rs
  packages/yew-agent/src/pool.rs
  packages/yew-agent/src/worker/mod.rs
  packages/yew-agent/src/worker/private.rs
  packages/yew-agent/src/worker/public.rs
  packages/yew-agent/src/worker/queue.rs
  packages/yew/src/html/conversion.rs
Labels: A-yew-agent

#2321 Overhaul Documentation
  website/docs/concepts/components/introduction.mdx
  website/docs/concepts/components/lifecycle.mdx
  website/docs/concepts/html/conditional-rendering.mdx
  website/docs/concepts/html/introduction.mdx
  website/docs/concepts/wasm-bindgen/introduction.mdx
  website/docs/concepts/wasm-bindgen/web-sys.mdx
  website/docs/getting-started/build-a-sample-app.mdx
  website/docs/getting-started/editor-setup.mdx
  website/docs/getting-started/examples.mdx
  website/docs/getting-started/introduction.mdx
  website/docs/getting-started/project-setup/using-trunk.mdx
  website/docs/getting-started/project-setup/using-wasm-pack.mdx
  website/docs/getting-started/starter-templates.mdx
  website/docs/more/css.mdx
  website/docs/more/testing.mdx
  website/docs/more/wasm-build-tools.mdx
  website/docusaurus.config.js
  website/package-lock.json
  website/sidebars.js
  website/versioned_docs/version-0.18.0/getting-started/introduction.mdx
  website/versioned_docs/version-0.19.0/getting-started/introduction.mdx
  website/versioned_docs/version-0.19.0/getting-started/project-setup/introduction.mdx
  website/versioned_sidebars/version-0.18.0-sidebars.json
  website/versioned_sidebars/version-0.19.0-sidebars.json
Labels: documentation

#2334 Bump MSRV to 1.56
  .github/workflows/pull-request.yml
  CONTRIBUTING.md
  README.md
  packages/yew-macro/Cargo.toml
  packages/yew-macro/Makefile.toml
  packages/yew-macro/tests/classes_macro_test.rs
  packages/yew-macro/tests/derive_props/fail.stderr
  packages/yew-macro/tests/derive_props_test.rs
  packages/yew-macro/tests/function_attr_test.rs
  packages/yew-macro/tests/function_component_attr/bad-return-type-fail.stderr
  packages/yew-macro/tests/function_component_attr/generic-props-fail.stderr
  packages/yew-macro/tests/html_macro/block-fail.stderr
  packages/yew-macro/tests/html_macro/component-fail.stderr
  packages/yew-macro/tests/html_macro/element-fail.stderr
  packages/yew-macro/tests/html_macro/iterable-fail.stderr
  packages/yew-macro/tests/html_macro/node-fail.stderr
  packages/yew-macro/tests/html_macro_test.rs
  packages/yew-macro/tests/props_macro/props-fail.stderr
  packages/yew-macro/tests/props_macro/resolve-prop-fail.stderr
  packages/yew-macro/tests/props_macro_test.rs
  packages/yew-router-macro/Cargo.toml
  packages/yew-router-macro/Makefile.toml
  packages/yew-router-macro/tests/routable_derive_test.rs
  packages/yew-router/Cargo.toml
  packages/yew/Cargo.toml
  website/versioned_docs/version-0.19.0/getting-started/introduction.mdx
Labels: breaking change, A-yew-router, A-yew, A-yew-agent

#2332 Fixed pub_sub link to point to correct example
  website/versioned_docs/version-0.19.0/concepts/agents.mdx
Labels: documentation

#2336 Replace Model with App or MyComponent
  CHANGELOG.md
  examples/agents/src/bin/app.rs
  examples/agents/src/lib.rs
  examples/boids/src/main.rs
  examples/contexts/src/main.rs
  examples/counter/src/main.rs
  examples/dyn_create_destroy_apps/src/main.rs
  examples/file_upload/src/main.rs
  examples/futures/src/main.rs
  examples/game_of_life/src/main.rs
  examples/inner_html/src/main.rs
  examples/js_callback/src/main.rs
  examples/keyed_list/src/main.rs
  examples/mount_point/src/main.rs
  examples/node_refs/src/main.rs
  examples/portals/src/main.rs
  examples/router/src/main.rs
  examples/timer/src/main.rs
  examples/todomvc/src/main.rs
  examples/two_apps/src/main.rs
  examples/web_worker_fib/src/app.rs
  examples/web_worker_fib/src/lib.rs
  examples/webgl/src/main.rs
  packages/yew/src/lib.rs
  website/docs/getting-started/build-a-sample-app.mdx
Labels: A-examples

#2347 Fixed broken link to getting-started/introduction
  website/src/pages/index.mdx
Labels: documentation

#2346 Remove start_app_as_body.
  packages/yew/src/app_handle.rs
  packages/yew/src/lib.rs
  website/docs/migration-guides/yew/from-0_19_0-to-0_20_0.mdx
Labels: breaking change, A-yew

#2352 Benchmarks completely redone
  .github/workflows/benchmark.yml
  Cargo.toml
  tools/benchmark-hooks/.gitignore
  tools/benchmark-hooks/Cargo.toml
  tools/benchmark-hooks/README.md
  tools/benchmark-hooks/index.html
  tools/benchmark-hooks/package-lock.json
  tools/benchmark-hooks/package.json
  tools/benchmark-hooks/src/lib.rs
  tools/benchmark-struct/.gitignore
  tools/benchmark-struct/Cargo.toml
  tools/benchmark-struct/README.md
  tools/benchmark-struct/index.html
  tools/benchmark-struct/package-lock.json
  tools/benchmark-struct/package.json
  tools/benchmark-struct/src/lib.rs
  tools/process-benchmark-results/Cargo.toml
  tools/process-benchmark-results/README.md
  tools/process-benchmark-results/src/main.rs
Labels: meta

#2355 fix failing PR's because of benchmarks
  .github/workflows/benchmark.yml
Labels: meta

#2356 fix benchmarks on pr's
  .github/workflows/benchmark.yml
Labels: meta

#2357 up alert treshold for benchmarks
  .github/workflows/benchmark.yml
Labels: meta

#2362 stop spamming bench comments on PR's
  .github/workflows/benchmark.yml
Labels: meta

#2345 Support named wildcards when deriving Routable.
  packages/yew-router-macro/src/routable_derive.rs
  packages/yew-router-macro/tests/routable_derive/valid-pass.rs
  packages/yew-router/src/switch.rs
  website/docs/concepts/router.mdx
Labels: A-yew-router

#2363 Remove important note from API docs
  packages/yew/src/lib.rs
Labels: documentation

#2255 example of function memory game
  Cargo.toml
  examples/function_memory_game/Cargo.toml
  examples/function_memory_game/README.md
  examples/function_memory_game/index.html
  examples/function_memory_game/public/8-ball.png
  examples/function_memory_game/public/back.png
  examples/function_memory_game/public/baked-potato.png
  examples/function_memory_game/public/dinosaur.png
  examples/function_memory_game/public/favicon.ico
  examples/function_memory_game/public/kronos.png
  examples/function_memory_game/public/rocket.png
  examples/function_memory_game/public/skinny-unicorn.png
  examples/function_memory_game/public/that-guy.png
  examples/function_memory_game/public/zeppelin.png
  examples/function_memory_game/scss/chess_board.scss
  examples/function_memory_game/scss/chess_board_card.scss
  examples/function_memory_game/scss/game_progress.scss
  examples/function_memory_game/scss/game_status_board.scss
  examples/function_memory_game/scss/index.scss
  examples/function_memory_game/scss/score_board.scss
  examples/function_memory_game/scss/score_board_best_score.scss
  examples/function_memory_game/src/components.rs
  examples/function_memory_game/src/components/app.rs
  examples/function_memory_game/src/components/chessboard.rs
  examples/function_memory_game/src/components/chessboard_card.rs
  examples/function_memory_game/src/components/game_status_board.rs
  examples/function_memory_game/src/components/score_board.rs
  examples/function_memory_game/src/components/score_board_best_score.rs
  examples/function_memory_game/src/components/score_board_logo.rs
  examples/function_memory_game/src/components/score_board_progress.rs
  examples/function_memory_game/src/constant.rs
  examples/function_memory_game/src/helper.rs
  examples/function_memory_game/src/main.rs
  examples/function_memory_game/src/state.rs
Labels: A-examples

#2335 Server-side Rendering (without hydration)
  .github/workflows/publish-examples.yml
  Cargo.toml
  Makefile.toml
  examples/futures/Cargo.toml
  examples/simple_ssr/Cargo.toml
  examples/simple_ssr/README.md
  examples/simple_ssr/src/main.rs
  examples/suspense/Cargo.toml
  packages/yew/Cargo.toml
  packages/yew/Makefile.toml
  packages/yew/src/functional/hooks/use_effect.rs
  packages/yew/src/html/component/lifecycle.rs
  packages/yew/src/html/component/scope.rs
  packages/yew/src/io_coop.rs
  packages/yew/src/lib.rs
  packages/yew/src/server_renderer.rs
  packages/yew/src/suspense/component.rs
  packages/yew/src/suspense/suspension.rs
  packages/yew/src/virtual_dom/vcomp.rs
  packages/yew/src/virtual_dom/vlist.rs
  packages/yew/src/virtual_dom/vnode.rs
  packages/yew/src/virtual_dom/vsuspense.rs
  packages/yew/src/virtual_dom/vtag.rs
  packages/yew/src/virtual_dom/vtext.rs
  packages/yew/tests/suspense.rs
  tools/website-test/Cargo.toml
  tools/website-test/build.rs
  website/docs/advanced-topics/server-side-rendering.md
  website/docs/concepts/suspense.md
  website/sidebars.js
Labels: A-yew

#2368 remove issue hunt link in footer
  website/docusaurus.config.js
Labels: documentation

#2371 Setup hosting for API docs
  .firebaserc
  .github/workflows/build-api-docs.yml
  .github/workflows/publish-api-docs.yml
  firebase.json
  tools/changelog/src/write_version_changelog.rs
Labels: documentation, meta

#2361 Add implementation types to examples table
  examples/README.md
Labels: A-examples, documentation

#2380 resolve some dead links as mentioned in issue #2379
  packages/yew/src/lib.rs
  website/docs/tutorial.mdx
Labels: documentation

#2390 Add community page using docs multi-instance
  website/community/awesome.md
  website/community/external-libs.mdx
  website/docusaurus.config.js
  website/i18n/ja/docusaurus-plugin-content-docs-community/current.json
  website/i18n/ja/docusaurus-plugin-content-docs-router/current.json
  website/i18n/ja/docusaurus-theme-classic/navbar.json
  website/i18n/zh-CN/docusaurus-plugin-content-docs-community/current.json
  website/i18n/zh-CN/docusaurus-plugin-content-docs-router/current.json
  website/i18n/zh-CN/docusaurus-theme-classic/navbar.json
  website/i18n/zh-TW/docusaurus-plugin-content-docs-community/current.json
  website/i18n/zh-TW/docusaurus-plugin-content-docs-router/current.json
  website/i18n/zh-TW/docusaurus-theme-classic/navbar.json
  website/package-lock.json
  website/sidebars/community.js
  website/sidebars/docs.js
Labels: documentation

#2391 Documentation Improvements
  website/blog/2022-01-20-hello-yew.md
  website/blog/authors.yml
  website/docs/tutorial/index.mdx
  website/docusaurus.config.js
  website/i18n/ja/docusaurus-plugin-content-blog/options.json
  website/i18n/ja/docusaurus-plugin-content-docs/current.json
  website/i18n/ja/docusaurus-theme-classic/navbar.json
  website/i18n/zh-CN/docusaurus-plugin-content-blog/options.json
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  website/i18n/zh-CN/docusaurus-theme-classic/navbar.json
  website/i18n/zh-TW/docusaurus-plugin-content-blog/options.json
  website/i18n/zh-TW/docusaurus-plugin-content-docs/current.json
  website/i18n/zh-TW/docusaurus-theme-classic/navbar.json
  website/sidebars/docs.js
  website/src/constants.js
  website/src/theme/NavbarItem/DefaultNavbarItem.tsx
  website/versioned_docs/version-0.19.0/tutorial/index.mdx
  website/versioned_sidebars/version-0.19.0-sidebars.json
Labels: documentation

#2395 fix CI clippy
  tools/benchmark-hooks/Cargo.toml
  tools/benchmark-struct/Cargo.toml
Labels: meta

#2372 Add ContextHandle in yew::prelude
  packages/yew/src/lib.rs
Labels: A-yew

#2404 Tidy up the documentation.
  website/docs/advanced-topics/how-it-works.mdx
  website/docs/advanced-topics/portals.mdx
  website/docs/concepts/html/events.mdx
  website/docs/concepts/wasm-bindgen/introduction.mdx
  website/docs/getting-started/build-a-sample-app.mdx
  website/docs/getting-started/examples.mdx
  website/docs/getting-started/introduction.mdx
  website/docs/migration-guides/yew-agent/from-0_1_0-to-0_2_0.mdx
  website/docs/migration-guides/yew-router/from-0_15_0-to-0_16_0.mdx
  website/docs/migration-guides/yew/from-0_18_0-to-0_19_0.mdx
  website/docs/more/roadmap.mdx
  website/docs/more/testing.mdx
  website/versioned_docs/version-0.19.0/concepts/html/events.mdx
  website/versioned_docs/version-0.19.0/concepts/wasm-bindgen/introduction.mdx
Labels: documentation

#2416 Make benchmarks run on head_ref
  .github/workflows/benchmark.yml
Labels: meta

#2419 Benchmark action specify repository
  .github/workflows/benchmark.yml
Labels: meta

#2401 Function Components & Hooks V2
  examples/function_todomvc/src/hooks/use_bool_toggle.rs
  examples/simple_ssr/src/main.rs
  examples/suspense/src/use_sleep.rs
  packages/yew-agent/src/hooks.rs
  packages/yew-macro/Cargo.toml
  packages/yew-macro/src/function_component.rs
  packages/yew-macro/src/hook/body.rs
  packages/yew-macro/src/hook/lifetime.rs
  packages/yew-macro/src/hook/mod.rs
  packages/yew-macro/src/hook/signature.rs
  packages/yew-macro/src/lib.rs
  packages/yew-macro/tests/function_component_attr/generic-props-fail.stderr
  packages/yew-macro/tests/function_component_attr/hook_location-fail.rs
  packages/yew-macro/tests/function_component_attr/hook_location-fail.stderr
  packages/yew-macro/tests/function_component_attr/hook_location-pass.rs
  packages/yew-router/src/hooks.rs
  packages/yew/Cargo.toml
  packages/yew/src/functional/hooks/mod.rs
  packages/yew/src/functional/hooks/use_context.rs
  packages/yew/src/functional/hooks/use_effect.rs
  packages/yew/src/functional/hooks/use_memo.rs
  packages/yew/src/functional/hooks/use_reducer.rs
  packages/yew/src/functional/hooks/use_ref.rs
  packages/yew/src/functional/hooks/use_state.rs
  packages/yew/src/functional/mod.rs
  packages/yew/src/virtual_dom/vsuspense.rs
  packages/yew/tests/mod.rs
  packages/yew/tests/suspense.rs
  packages/yew/tests/use_context.rs
  packages/yew/tests/use_effect.rs
  packages/yew/tests/use_memo.rs
  packages/yew/tests/use_reducer.rs
  packages/yew/tests/use_ref.rs
  packages/yew/tests/use_state.rs
  website/docs/concepts/function-components/custom-hooks.mdx
  website/docs/concepts/function-components/introduction.mdx
  website/docs/concepts/function-components/pre-defined-hooks.mdx
  website/docs/concepts/suspense.mdx
  website/docs/migration-guides/yew/from-0_19_0-to-0_20_0.mdx
Labels: breaking change, A-yew, A-yew-macro

#2420 Do not detach child elements if parent element is about to be detached
  packages/yew/src/app_handle.rs
  packages/yew/src/html/component/lifecycle.rs
  packages/yew/src/html/component/scope.rs
  packages/yew/src/virtual_dom/mod.rs
  packages/yew/src/virtual_dom/vcomp.rs
  packages/yew/src/virtual_dom/vlist.rs
  packages/yew/src/virtual_dom/vnode.rs
  packages/yew/src/virtual_dom/vportal.rs
  packages/yew/src/virtual_dom/vsuspense.rs
  packages/yew/src/virtual_dom/vtag.rs
  packages/yew/src/virtual_dom/vtext.rs
Labels: performance, A-yew

#2417 Add Other variant to the ListenerKind
  packages/yew/src/virtual_dom/listeners.rs
Labels: breaking change, A-yew

#2426 run npm run write-translations
  website/i18n/ja/code.json
  website/i18n/ja/docusaurus-plugin-content-blog/options.json
  website/i18n/ja/docusaurus-plugin-content-docs-community/current.json
  website/i18n/ja/docusaurus-plugin-content-docs/current.json
  website/i18n/ja/docusaurus-plugin-content-docs/version-0.18.0.json
  website/i18n/ja/docusaurus-plugin-content-docs/version-0.19.0.json
  website/i18n/ja/docusaurus-theme-classic/footer.json
  website/i18n/ja/docusaurus-theme-classic/navbar.json
  website/i18n/zh-CN/code.json
  website/i18n/zh-CN/docusaurus-plugin-content-blog/options.json
  website/i18n/zh-CN/docusaurus-plugin-content-docs-community/current.json
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.18.0.json
  website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.19.0.json
  website/i18n/zh-CN/docusaurus-theme-classic/footer.json
  website/i18n/zh-CN/docusaurus-theme-classic/navbar.json
  website/i18n/zh-TW/code.json
  website/i18n/zh-TW/docusaurus-plugin-content-blog/options.json
  website/i18n/zh-TW/docusaurus-plugin-content-docs-community/current.json
  website/i18n/zh-TW/docusaurus-plugin-content-docs/current.json
  website/i18n/zh-TW/docusaurus-plugin-content-docs/version-0.18.0.json
  website/i18n/zh-TW/docusaurus-plugin-content-docs/version-0.19.0.json
  website/i18n/zh-TW/docusaurus-theme-classic/footer.json
  website/i18n/zh-TW/docusaurus-theme-classic/navbar.json
Labels: meta

#2427 Update references to gitlocalize project
  README.md
  website/README.md
Labels: meta
