Repository yewstack/yew, pull requests merged in 2022-11, with the labels that each got.

#2836 Fix code listing in tutorial/index.mdx
  website/docs/tutorial/index.mdx
  website/versioned_docs/version-0.19.0/tutorial/index.mdx
Labels: documentation, S-waiting-on-author

#2883 Proposed Documentation Improvements
  website/docs/concepts/basic-web-technologies/wasm-bindgen.mdx
  website/versioned_docs/version-0.19.0/concepts/wasm-bindgen/introduction.mdx
Labels: S-waiting-on-author

#2928 Improve debugging page in docs
  website/docs/more/debugging.mdx
Labels: documentation

#2842 Add VNode::from_html_unchecked
  examples/inner_html/src/document.html
  examples/inner_html/src/main.rs
  packages/yew/Cargo.toml
  packages/yew/src/dom_bundle/bnode.rs
  packages/yew/src/dom_bundle/braw.rs
  packages/yew/src/dom_bundle/btag/mod.rs
  packages/yew/src/dom_bundle/mod.rs
  packages/yew/src/dom_bundle/traits.rs
  packages/yew/src/dom_bundle/utils.rs
  packages/yew/src/virtual_dom/mod.rs
  packages/yew/src/virtual_dom/vnode.rs
  packages/yew/src/virtual_dom/vraw.rs
  packages/yew/tests/raw_html.rs
Labels: breaking change, A-yew

#2954 Fix changelog workflow
  .github/workflows/inspect-next-changelogs.yml
Labels: A-ci

#2985 Add yew-agent repository, homepage, documentation
  packages/yew-agent/Cargo.toml
Labels: meta

#2986 Fix release actions
  .github/workflows/publish-yew-agent.yml
  .github/workflows/publish-yew-only.yml
  .github/workflows/publish-yew-router-only.yml
  .github/workflows/publish-yew-router.yml
  .github/workflows/publish-yew.yml
Labels: meta
