Repository yewstack/yew, pull requests merged in 2023-02, with the labels that each got.

#3101 Separate PR and master size collection
  .github/workflows/post-size-cmp.yml
  .github/workflows/size-cmp.yml
  ci/collect_sizes.py
  ci/make_example_size_cmt.py
Labels: A-ci

#2872 Pass string types to Html props
  examples/suspense/README.md
  packages/yew-macro/tests/html_macro/component-pass.rs
  packages/yew-macro/tests/html_macro/element-fail.stderr
  packages/yew/src/html/conversion.rs
  packages/yew/src/suspense/component.rs
Labels: A-yew

#3098 Update examples/README with correct starter templates link
  examples/README.md
Labels: documentation
