Repository yewstack/yew, pull requests merged in 2023-11, with the labels that each got.

#3518 Update to Docusaurus v3
  .github/workflows/build-website.yml
  website/docs/getting-started/build-a-sample-app.mdx
  website/docs/getting-started/examples.mdx
  website/docs/tutorial/index.mdx
  website/docusaurus.config.js
  website/i18n/ja/code.json
  website/i18n/ja/docusaurus-plugin-content-docs/version-0.18.0.json
  website/i18n/ja/docusaurus-plugin-content-docs/version-0.18.0/getting-started/choose-web-library.mdx
  website/i18n/ja/docusaurus-plugin-content-docs/version-0.19.0.json
  website/i18n/zh-Hans/code.json
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/advanced-topics/optimizations.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/concepts/html/components.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/getting-started/build-a-sample-app.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/version-0.18.0.json
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/version-0.18.0/concepts/html/components.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/version-0.18.0/getting-started/build-a-sample-app.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/version-0.18.0/getting-started/project-setup/using-trunk.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/version-0.19.0.json
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/version-0.20/advanced-topics/optimizations.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/version-0.20/concepts/html/components.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/version-0.20/getting-started/build-a-sample-app.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/version-0.21/advanced-topics/optimizations.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/version-0.21/concepts/html/components.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/version-0.21/getting-started/build-a-sample-app.mdx
  website/i18n/zh-Hant/code.json
  website/i18n/zh-Hant/docusaurus-plugin-content-docs/current/concepts/html/components.mdx
  website/i18n/zh-Hant/docusaurus-plugin-content-docs/current/getting-started/build-a-sample-app.mdx
  website/i18n/zh-Hant/docusaurus-plugin-content-docs/version-0.18.0.json
  website/i18n/zh-Hant/docusaurus-plugin-content-docs/version-0.18.0/concepts/html/components.mdx
  website/i18n/zh-Hant/docusaurus-plugin-content-docs/version-0.18.0/getting-started/build-a-sample-app.mdx
  website/i18n/zh-Hant/docusaurus-plugin-content-docs/version-0.18.0/getting-started/choose-web-library.mdx
  website/i18n/zh-Hant/docusaurus-plugin-content-docs/version-0.18.0/getting-started/starter-templates.mdx
  website/i18n/zh-Hant/docusaurus-plugin-content-docs/version-0.19.0.json
  website/i18n/zh-Hant/docusaurus-plugin-content-docs/version-0.20/concepts/html/components.mdx
  website/i18n/zh-Hant/docusaurus-plugin-content-docs/version-0.20/getting-started/build-a-sample-app.mdx
  website/i18n/zh-Hant/docusaurus-plugin-content-docs/version-0.21/concepts/html/components.mdx
  website/i18n/zh-Hant/docusaurus-plugin-content-docs/version-0.21/getting-started/build-a-sample-app.mdx
  website/package-lock.json
  website/package.json
  website/tsconfig.json
  website/versioned_docs/version-0.18.0/getting-started/build-a-sample-app.mdx
  website/versioned_docs/version-0.18.0/getting-started/project-setup/using-trunk.mdx
  website/versioned_docs/version-0.19.0/getting-started/project-setup/using-trunk.mdx
  website/versioned_docs/version-0.19.0/tutorial/index.mdx
  website/versioned_docs/version-0.20/getting-started/build-a-sample-app.mdx
  website/versioned_docs/version-0.20/getting-started/examples.mdx
  website/versioned_docs/version-0.20/tutorial/index.mdx
  website/versioned_docs/version-0.21/getting-started/build-a-sample-app.mdx
  website/versioned_docs/version-0.21/getting-started/examples.mdx
  website/versioned_docs/version-0.21/tutorial/index.mdx
  website/versioned_sidebars/version-0.18.0-sidebars.json
  website/versioned_sidebars/version-0.19.0-sidebars.json
Labels: documentation, javascript

#3519 Add conversion from `UseStateSetter` & `UseReducerDispatcher` to a `Callback`
  packages/yew/src/functional/hooks/use_reducer.rs
  packages/yew/src/functional/hooks/use_state.rs
Labels: A-yew

#3522 Fix website search
  website/docusaurus.config.js
Labels: meta, javascript
